(() => {
const S={chat:"ron-chat-v2",lessons:"ron-lessons-v2"},$=id=>document.getElementById(id),chat=$("chat"),form=$("composer"),input=$("input"),send=$("send");
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=()=>{localStorage.setItem(S.chat,JSON.stringify(messages.slice(-200)));localStorage.setItem(S.lessons,JSON.stringify(lessons.slice(-500)))};
let messages=read(S.chat,[{role:"ron",text:"مرحبًا. أنا رون. النواة المحلية تعمل، وذاكرتي محفوظة على هذا الجهاز."}]),lessons=read(S.lessons,[]);
const bubble=(role,text)=>{const e=document.createElement("article");e.className="message "+role;const b=document.createElement("b"),p=document.createElement("p");b.textContent=role==="ron"?"رون":"أنت";p.textContent=text;e.append(b,p);chat.appendChild(e);chat.scrollTop=chat.scrollHeight};
const render=()=>{chat.replaceChildren();messages.forEach(m=>bubble(m.role,m.text))};
const norm=s=>s.toLowerCase().replace(/[ًٌٍَُِّْـ]/g,"").trim();
const teach=t=>{const x=t.replace(/^\s*عل[ّ]?م\s+رون\s*:\s*/i,"").trim();if(!x)return"اكتب المعلومة بعد «علّم رون:».";lessons.push({text:x,at:new Date().toISOString()});save();return"تم حفظ التعليم في ذاكرة رون المحلية."};
const answer=t=>{const n=norm(t);if(/^عل[ّ]?م رون\s*:/.test(n))return teach(t);if(n.includes("ماذا تعلمت")||n.includes("ما الذي تعلمته"))return lessons.length?"هذه آخر تعليماتي المحفوظة:\n\n"+lessons.slice(-10).map((x,i)=>i+1+". "+x.text).join("\n"):"لم تعلّمني شيئًا بعد.";if(n.includes("امسح الذاكره")||n.includes("امسح الذاكرة")){lessons=[];save();return"تم مسح الذاكرة التي علّمتني إياها."}if(/^(مرحبا|اهلا|أهلا|السلام عليكم)/.test(n))return"أهلًا بك. أنا رون. ابدأ بتعليمي أو اكتب أي شيء لتجربة النواة.";if(n.includes("من انت")||n.includes("من أنت"))return"أنا رون، مشروع مساعد مستقل. هذه النسخة تعمل محليًا بدون مفتاح API، بينما طبقة النموذج المتقدم ما زالت قيد البناء.";const hit=lessons.slice().reverse().find(x=>n.includes(norm(x.text).slice(0,Math.min(30,norm(x.text).length))));return hit?"أتذكر تعليمك: "+hit.text:"وصلتني رسالتك. النواة المحلية تعمل، لكن نموذج الاستدلال المتقدم لم يُوصل بعد. يمكنك تعليمي بكتابة «علّم رون: ...»."};
const sendMessage=()=>{const t=input.value.trim();if(!t)return;messages.push({role:"user",text:t});bubble("user",t);input.value="";input.style.height="auto";send.disabled=true;setTimeout(()=>{const r=answer(t);messages.push({role:"ron",text:r});bubble("ron",r);save();send.disabled=false;input.focus()},100)};
form.addEventListener("submit",e=>{e.preventDefault();sendMessage()});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,140)+"px"});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}});
$("menu").addEventListener("click",()=>$("settings").classList.add("open"));$("close-settings").addEventListener("click",()=>$("settings").classList.remove("open"));$("new-chat").addEventListener("click",()=>{messages=[{role:"ron",text:"بدأنا محادثة جديدة. كيف يمكنني مساعدتك؟"}];save();render();$("settings").classList.remove("open")});
$("clear-data").addEventListener("click",()=>{if(confirm("مسح كل بيانات رون المحلية؟")){localStorage.clear();location.reload()}});
$("export").addEventListener("click",()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify({version:1,exportedAt:new Date().toISOString(),messages,lessons},null,2)],{type:"application/json"}));a.download="ron-backup.json";a.click()});
$("import").addEventListener("change",async e=>{const f=e.target.files[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.messages)||!Array.isArray(d.lessons))throw 0;messages=d.messages;lessons=d.lessons;save();render();alert("تم استيراد ذاكرة رون.")}catch{alert("ملف النسخ الاحتياطي غير صالح.")}e.target.value=""});render();
})();